var quotesLength;
var randomQuoteIndex;
var randomQuoteText;
const quotes = [
    "Will you regret if you do not do this?",
    "If the world were as we imagine it, it would be completely different",
    "Humans can do what he wants, but it is not up to him to decide what he wants",
    "The power of science in not being afraid of reinventing things",
    "Life is not about finding yourself, it is about creating yourself",
    "Life is a tragedy for those who feel, and a comedy for those who think",
    "When you understand the game you do not panic",
    "We are the raw material from which dreams are made, and life is a waking moment between two dreams",
    "It was found that the brain expects what it should see, inferring from the accumulated knowledge and what has happened before. It prepares a predicted picture of what the eyes should see. This information travels from the brain to the eyes, overcoming a whole series of intermediate points. Nervous systems only send signals to the brain when a discrepancy is detected between what the brain expected and the light reaching the eyes. Thus, images of our surroundings are not transmitted from the eyes to the brain - only information about incompatibility with what the brain expects reaches there",
    "80% of our bad behavior is attributable to a version of ourselves that exists only 20% of the time",
    "To replace programmers with AI, clients will need to describe what they want accurately",
    "The stage at which the naked monkey is now is also a temporary, relatively primitive stage of development. In time we will be evolutionarily replaced by beings who will be separated from us by a gap much larger than the one that separates us from ants. [...] To speak with certainty about anything is therefore not only insolence but what is worse - tactless",
    "Before you heal someone, ask him if he is willing to give up the things that make him sick",
    "Do not say things you do not mean and do not go with things you do not agree with",
    "The world will ask you who you are, and if you do not know the world will tell you",
    "Everything that irritates us about others can lead us to an understanding of ourselves",
    "If you get tired, learn to rest. Not to quit",
    "If having a coffee in the morning does not wake you up, try deleting a table in a production database instead",
    "Nothing can destroy iron, only its own rust can. Likewise, nothing can destroy you, only your own mindset can",
    "Treat yourself like a Porsche",
    "How does mom wake up at eight? Get up, you can not stay like this forever",
    "What does zero say to eight - nice bar",
    "The integral enters the train, and this is not its interval",
    "Talent without hard work is nothing",
    "There are two ways to live life. One is to live as if nothing is a miracle. The second is to live as if everything were a miracle",
    "Our life is what our thoughts make it",
    "There is nothing permanent except change",
    "Never give up on a dream just because it takes time to realize it. Time will pass anyway",
    "The greatest glory is not in never falling, but in being able to get up every time we fall",
    "If you cannot fly, run. If you cannot run, walk. If you cannot walk, crawl. Whatever you do, keep moving forward",
    "Success is the sum of small efforts repeated day after day",
    "Don't wait. The time will never be perfect",
    "Be yourself, everyone else is already taken",
    "The best way to predict the future is to create it",
    "If the brain will so simple that we could understand it, we would be so simple that we could not do it",
    "The essence of instinct is that it operates independently of reason",
    "Dreaming is a form of planning",
    "Simplicity may be more difficult than complexity: you must work hard to extract the clear thought that allows for simplicity. But it is worth it because once you have it, you can move mountains",
    "Any job can be done if you divide it into small sections",
    "Small opportunities are often the beginning of great ventures",
    "When a person cannot find a deep sense of meaning, they distract themselves with pleasure",
    "Change happens when the pain of staying the same is greater than the pain of change",
    "Dear Math, please grow up and solve your problems by yourself :)",
    "Science is food for the mind",
    "Make lots of mistakes and learn from them",
    "Don't expect better results if you keep doing the same thing. Maintain your childlike curiosity",
    "Success can be learned",
    "Science is magic that really works",
    "You should spend a little more time working on yourself and a little less time trying to impress others",
    "The beautiful thing about learning is that nobody can take it away from you",
    "Do NOT buy things you do not need with money you do not have",
    "Water is the only drink for wise people",
    "Most shadows in our lives are created when we block our sun",
    "Everything should be constructed as simply as possible, but not simplistic",
    "Good luck is not a coincidence",
    "Fake it until you make it",
    "When you know that delusion is a way of manifestation",
    "If someone is hotter than you then you are cooler than them. - Thermodynamics",
    "Once you see the road, you will see it everywhere",
    "The best thing you have ever done is that you never stopped",
    "If we don't have a lifelong financial plan, we have an unplanned recipe for poverty",
    "Do you believe it, can you receive it?",
    "Why do you always find what you are looking for at the very end? Because once you find it, you stop looking",
    "A system that rewards 'valuable failures'",
    "Our choices reflect who we really are, much more than our capabilities",
    "I am capacious, I contain millions (human)",
    "Shame ends where human is ready to meet human in truth...",
    "Do NOT spend most of your life worrying about things that will never happen",
    "The idea is a piece of cake, the most important thing is the execution",
    "A house that has no windows, doors, and locks attracts people who do not treat it with respect",
    "If you do something for yourself, don't do it at the expense of others. If you do something for others, don't do it at the expense of yourself",
    "We have two lives. The second one begins when we realize we only have one",
    "Spend each day in such a way that you go to sleep a little smarter than you were when you woke up in the morning",
    "If you don't make time to take care of yourself, you'll have to make time to be sick",
    "I am afraid if I stop I will discover I am dead",
    "It is not a measure of health to be well adapted to a deeply sick society",
    "Those who are not confused by the situation don’t really understand what is going on",
    "Fortune will favor the adaptable mind",
    "You are your only limit",
    "Honesty in small things is not a small thing",
    "Try to leave this world a little better than you found it",
    "If you think you can do it, you're right, if you think you can't do it, you're also right",
    "Invest in the habits, and your body will perform",
    "Change is hard, being miserable is harder",
    "If you want to go fast, go alone; if you want to go far, go together",
    "If you do not know where you are going, you might end up somewhere else",
    "You are worth as much as you are able to give to others",
    "Run after your dreams, if you don't reach them, at least you'll lose weight."
];

function randomQuote() {

    quotesLength = quotes.length;
    randomQuoteIndex = Math.floor((Math.random() * quotesLength)+1);
    randomQuoteText = quotes[randomQuoteIndex];
   
    document.getElementById("quote").innerHTML = randomQuoteText;

};
